<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveCategories()
    {
        return $this->createQueryBuilder('category')
            ->andWhere('category.isDeleted = :isDeleted')
            ->setParameter('isDeleted', false)
            ->getQuery()
            ->execute();
    }

    public function findAllDeletedCategories()
    {
        return $this->createQueryBuilder('category')
            ->andWhere('category.isDeleted = :isDeleted')
            ->setParameter('isDeleted', true)
            ->getQuery()
            ->execute();
    }
}
