<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActivePromotions()
    {
        return $this->createQueryBuilder('promotion')
            ->andWhere('promotion.isDeleted = :isDeleted')
            ->setParameter('isDeleted', false)
            ->getQuery()
            ->execute();
    }

    public function findAllDeletedPromotions()
    {
        return $this->createQueryBuilder('promotion')
            ->andWhere('promotion.isDeleted = :isDeleted')
            ->setParameter('isDeleted', true)
            ->getQuery()
            ->execute();
    }
}
