<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;


/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveReviewsForProduct(Product $product)
    {
        return $this->createQueryBuilder('review')
            ->andWhere('review.product = :product')
            ->setParameter('product', $product)
            ->getQuery()
            ->execute();
    }
}
